### PR TITLE
Person search & only tv or only movie search

### PR DESCRIPTION
**Pull request by Primdahl26**
### Is your feature request related to a problem? Please describe.

I would like us to be able to search for people on the index page.

### Describe the solution you'd like

I would like a select at the right of the input field where you can choose one of 4 options: `['TV & movies', 'Movies', 'TV', 'People']`  

### Describe alternatives you've considered

The multi selects should dissapear when people are chosen.

### Additional context

This is a larger todo, but would improve the experience by quite a lot. This will require a download of all people from TMDB, and a meilisearch indexing of them. Will also need endpoint handling for media or tv alone, and one for people. Beyond that the frontend will also need to handle this.

To get people data we can use: https://developers.themoviedb.org/3/getting-started/daily-file-exports

### CODE REVIEW

**Comment by AndreasPB** [comment]
@Primdahl26 The movie/tv filter was done in different PRs #257 and #259, but I guess the person thing still needs to be done at some point... wat do? :D

**Comment by nullxDEADBEEF** [comment]
Congratulations PR, you have survived long! :partying_face:

**Comment by AndreasPB** [comment]
This should be an issue again

**Comment by AndreasPB** [comment]
Lives in #319 now

**Pull request closed without merging**
