### PR TITLE
Make recommendations scrollable by replacing carousel with swiper-component

### PR DESCRIPTION
**Pull request by Pankai222**

### CODE REVIEW

**Comment by Primdahl26** [comment]
Feels very nice! But can we maybe add infinite scrolling or some of the cool features of swiper?

Also, there seems to be a weird scrolling dead zones between the images.

**Comment by Pankai222** [comment]
> Feels very nice! But can we maybe add infinite scrolling or some of the cool features of swiper?
> 
> Also, there seems to be a weird scrolling dead zones between the images.

**Comment by Pankai222** [comment]
@Primdahl26 not being able to swipe between slides is addressed in this issue: https://github.com/nolimits4web/swiper/issues/5559 and has no viable workaround for our case right now :( 

I have implemented infinite loop for the recommendations that are already loaded for the media.

**Review by AndreasPB — APPROVED** [review]

**Comment by Caesarzk** [comment]
Drugging in the space works only at 1st group of slides! After swipe to another group it doesn't work

**Pull request merged**
